<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Selamat Datang_nip (1)</name>
   <tag></tag>
   <elementGuidId>7df24018-5cd2-4d44-85a4-c55fd09aeb5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nip</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nip']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>99dee5a2-044b-4035-ba3b-a725a5a92552</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nip</value>
      <webElementGuid>ea404bad-2b72-4e47-b432-818a82ac6434</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c8816cb1-0522-4974-8338-04d9f05d81fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>d3eca8f5-ea3b-4b3c-9743-d2244cc27862</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nip</value>
      <webElementGuid>2edb88ae-9b9e-4df5-81e9-4acae52329e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>NIP</value>
      <webElementGuid>d2119d84-0f4e-4d9d-a0e6-f20139e98b1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nip&quot;)</value>
      <webElementGuid>3f9a3adc-7852-4b19-8f41-2011442fc591</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nip']</value>
      <webElementGuid>981bb9a9-e0a5-42ed-a436-436acf1ee524</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>cd480c9d-e5cb-4bd1-94d2-65c21534eb31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'nip' and @type = 'text' and @id = 'nip' and @placeholder = 'NIP']</value>
      <webElementGuid>d6c09411-6aaa-4953-b895-4b10a1846f85</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
