<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Jabatan Pegawai_jabatan</name>
   <tag></tag>
   <elementGuidId>ae5c7f04-8d21-43e3-9738-c8cabff961d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;jabatan&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='jabatan']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fca22ef6-bc1d-47fb-8b69-99197225a463</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>84af1673-6a30-4ec0-860b-10ac1abfc2ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>jabatan</value>
      <webElementGuid>5649940e-2f42-49e5-b0fc-c4189571aadc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e735490a-e05f-470a-b4c1-53c857cc22e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;container-fluid vh-100 bg-light&quot;]/main[@class=&quot;row&quot;]/content[@class=&quot;col&quot;]/div[@class=&quot;p-5&quot;]/form[@class=&quot;border rounded p-4 bg-white shadow-sm&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;mb-3 col-md-6&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>3937a578-88d5-432d-8695-8a018f317300</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='jabatan']</value>
      <webElementGuid>1bfca446-638d-4650-b9ac-e3cccd92cd41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>3068f9f7-4deb-44d1-b58e-a1ab8b88d3b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'jabatan']</value>
      <webElementGuid>92ed017e-650b-44b4-b16e-a3963df1791b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
