<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nomor Telepon_no_telp</name>
   <tag></tag>
   <elementGuidId>5ce5e9fe-631e-4445-8b61-803288a8b35a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;no_telp&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='no_telp']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9f3b17ad-9769-4b9f-974c-2b742ec14463</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>a558b033-37a1-4f36-b689-ff4bc75c941e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>no_telp</value>
      <webElementGuid>0ef12c81-42c7-4bff-acd3-8910a879cccb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>66c26ee9-4225-480d-a46d-2ae1f8ee9529</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;container-fluid vh-100 bg-light&quot;]/main[@class=&quot;row&quot;]/content[@class=&quot;col&quot;]/div[@class=&quot;p-5&quot;]/form[@class=&quot;border rounded p-4 bg-white shadow-sm&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;mb-3 col-md-4&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>0d9646b4-57fc-48e5-beb6-fa99cd154762</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='no_telp']</value>
      <webElementGuid>31056225-3db7-4834-829a-aab69f9c2b05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>f7a8d7df-5962-40eb-ae6a-a7c0ec9a3e5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @name = 'no_telp']</value>
      <webElementGuid>89eccaac-5650-46b1-8468-b0f82276b1ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
