<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Manajer_menu-button</name>
   <tag></tag>
   <elementGuidId>01dd6b3e-1171-4c3e-9702-92fde6c26d93</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menu-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='menu-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0a261651-8cbe-4419-844a-543ebc67e9a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>menu1_manajer.php</value>
      <webElementGuid>0518378f-adc4-4e0f-8ccf-cc268ca578f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>py-2 px-4-5</value>
      <webElementGuid>f39a2391-439b-49f1-9471-7dea1c4de189</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menu-button</value>
      <webElementGuid>f27dd30f-b110-4c06-8cb6-33a7a4de01ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-button&quot;)</value>
      <webElementGuid>489c588f-8d48-4b52-b421-66860e6a8610</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='menu-button']</value>
      <webElementGuid>5dfaf213-67b2-455b-b173-e8ee5f59fe62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manajer'])[1]/following::a[1]</value>
      <webElementGuid>257d42ad-a266-4ac0-bb45-59bc13d4e464</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data Absensi'])[2]/preceding::a[2]</value>
      <webElementGuid>68f13136-ec0c-4b10-bc9c-a202976ff3df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/preceding::a[3]</value>
      <webElementGuid>781c59c8-e152-4970-9b00-3164b26a0fbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'menu1_manajer.php')]</value>
      <webElementGuid>6b7dfc47-7120-4e64-bb84-88d43a03b03e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/a</value>
      <webElementGuid>dc7487af-f87a-484e-b274-af7512726fea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'menu1_manajer.php' and @id = 'menu-button']</value>
      <webElementGuid>2de956c0-e837-4573-b432-226cdb142a35</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
