<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Karyawan</name>
   <tag></tag>
   <elementGuidId>effb4596-5995-40d2-9a37-c4272d9f75b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-light.shadow-sm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Karyawan')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f5c4614a-49f4-42ed-a0bb-c6722b8b2cbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>menu1_operator.php?sorting_jabatan=Karyawan</value>
      <webElementGuid>60311c0f-ccaf-440b-ae15-4ee8ee8ca559</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-light shadow-sm</value>
      <webElementGuid>507cf96b-5736-4e73-b022-2f26afcbe4e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Karyawan</value>
      <webElementGuid>23c5f79b-5b78-4224-afb3-5c85bbf9c700</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;container-fluid vh-100 bg-light&quot;]/main[@class=&quot;row&quot;]/content[@class=&quot;col&quot;]/div[@class=&quot;p-5&quot;]/div[@class=&quot;d-flex mb-4&quot;]/a[@class=&quot;btn btn-light shadow-sm&quot;]</value>
      <webElementGuid>a2f96675-150a-4a43-9bf7-f1b3abba129e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Karyawan')]</value>
      <webElementGuid>2a0d38d5-c3ee-4c9f-a189-bb4d16f987fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Semua'])[1]/following::a[1]</value>
      <webElementGuid>8a49abda-0535-493e-a1e8-021092923697</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keluar'])[1]/following::a[2]</value>
      <webElementGuid>b4a3da11-87bc-47c5-bcae-7e2537575d33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Operator'])[2]/preceding::a[1]</value>
      <webElementGuid>b3518432-a7fb-40c4-8dd2-cd2d52347378</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manajer'])[1]/preceding::a[2]</value>
      <webElementGuid>127fb3f3-0912-46ed-986d-6e81c544988d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Karyawan']/parent::*</value>
      <webElementGuid>92a13bbd-0631-44ce-9d4b-185c14a8e502</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'menu1_operator.php?sorting_jabatan=Karyawan')]</value>
      <webElementGuid>63dbda56-b619-4a64-9b65-2262f4acc9dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//content/div/div/a[2]</value>
      <webElementGuid>0ab97cea-3209-468e-9b81-852439102839</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'menu1_operator.php?sorting_jabatan=Karyawan' and (text() = 'Karyawan' or . = 'Karyawan')]</value>
      <webElementGuid>2de0035f-60d6-4e19-9112-7fde5aed5e83</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
