<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Manajer</name>
   <tag></tag>
   <elementGuidId>86ff4113-dd7f-4761-b000-339d40ba3963</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Manajer')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>87d9f138-f97e-4caa-866d-0d40fd4c2291</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>menu1_operator.php?sorting_jabatan=Manajer</value>
      <webElementGuid>b347efb3-cf81-446f-a022-935ee47fdc3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-light shadow-sm</value>
      <webElementGuid>08ee42b0-568e-414e-9c6d-078e1dcc1be2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Manajer</value>
      <webElementGuid>54643246-a6dc-4df8-95fb-b4271024a86a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;container-fluid vh-100 bg-light&quot;]/main[@class=&quot;row&quot;]/content[@class=&quot;col&quot;]/div[@class=&quot;p-5&quot;]/div[@class=&quot;d-flex mb-4&quot;]/a[@class=&quot;btn btn-light shadow-sm&quot;]</value>
      <webElementGuid>f4133d2d-f585-4e77-8747-8aef5a8a46cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Manajer')]</value>
      <webElementGuid>a5925a6c-16de-4dc9-9f6f-fc923d6c05fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Operator'])[2]/following::a[1]</value>
      <webElementGuid>5379d32f-1b4a-4b9b-9e24-54f7cf916c13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Karyawan'])[1]/following::a[2]</value>
      <webElementGuid>f6d0272e-e16a-450c-b235-21a33a6e50f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar Operator'])[1]/preceding::a[1]</value>
      <webElementGuid>7b3bf50b-af4c-4777-aa9d-86d6dac58347</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Divisi'])[1]/preceding::a[1]</value>
      <webElementGuid>2799c31c-58e6-4442-9d36-626f6d6cacc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Manajer']/parent::*</value>
      <webElementGuid>383ad628-dc77-4acb-b4ca-b088d5d6145c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'menu1_operator.php?sorting_jabatan=Manajer')]</value>
      <webElementGuid>bf5607fd-c815-4d54-b004-a1484295f359</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[4]</value>
      <webElementGuid>6c0fa50f-0c6a-4956-9b7f-08991ffa91ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'menu1_operator.php?sorting_jabatan=Manajer' and (text() = 'Manajer' or . = 'Manajer')]</value>
      <webElementGuid>1c413210-733d-4c43-a95e-42f70df876c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
