<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Operator</name>
   <tag></tag>
   <elementGuidId>cf0fcf8c-0325-47bb-9f03-a5fc24977103</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-light.rounded-0.shadow-sm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Operator')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0228dd31-78b5-4070-9329-db7cd40bcf26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>menu1_operator.php?sorting_jabatan=Operator</value>
      <webElementGuid>4e98e522-b1fb-43a6-8c17-2db6272130b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-light rounded-0 shadow-sm</value>
      <webElementGuid>a2d7700a-88ba-478f-86e2-222eca3b1cdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Operator</value>
      <webElementGuid>62cafe80-8cd3-487a-9568-26eeab702f2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;container-fluid vh-100 bg-light&quot;]/main[@class=&quot;row&quot;]/content[@class=&quot;col&quot;]/div[@class=&quot;p-5&quot;]/div[@class=&quot;d-flex mb-4&quot;]/a[@class=&quot;btn btn-light rounded-0 shadow-sm&quot;]</value>
      <webElementGuid>66ca2037-0537-4522-ac85-192f220427e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Operator')]</value>
      <webElementGuid>e30e4e09-ad93-463e-b3fb-76be23d44b77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Karyawan'])[1]/following::a[1]</value>
      <webElementGuid>0a368e27-df28-48c1-b788-6dc3bceefbad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Semua'])[1]/following::a[2]</value>
      <webElementGuid>48445808-859b-48d2-b798-9d0364886f02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manajer'])[1]/preceding::a[1]</value>
      <webElementGuid>84d5b383-36ca-4cda-bad6-d4dc3a7a53f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar Karyawan'])[1]/preceding::a[2]</value>
      <webElementGuid>626eff50-c702-454e-a868-eb8d246996b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'menu1_operator.php?sorting_jabatan=Operator')]</value>
      <webElementGuid>67e48890-3366-4f3d-aae3-dc22633e4d79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/a[3]</value>
      <webElementGuid>c42943be-e43e-4039-9cba-b24ae08fb722</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'menu1_operator.php?sorting_jabatan=Operator' and (text() = 'Operator' or . = 'Operator')]</value>
      <webElementGuid>e177ca65-f033-4d7e-be46-f477177ab5b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
