<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Operator_fa fa-user-plus fs-3</name>
   <tag></tag>
   <elementGuidId>fafe4d58-fa26-4881-97c8-ae0fa7bd9d2f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-user-plus.fs-3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='menu2-button']/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>9b7a9d14-7764-41ca-a077-56364df20936</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-user-plus fs-3</value>
      <webElementGuid>3c45cc41-f5bd-40ca-a9d0-c8c5651fd86d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu2-button&quot;)/i[@class=&quot;fa fa-user-plus fs-3&quot;]</value>
      <webElementGuid>76a7c8a3-0186-4805-b9ce-f307263f2c4f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='menu2-button']/i</value>
      <webElementGuid>71e51bfe-7283-4614-aa5a-6367ccbfe83e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/i</value>
      <webElementGuid>63ab275a-bde6-4f2b-b635-1fcf923cde96</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
