<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Manajer_logout-button</name>
   <tag></tag>
   <elementGuidId>97288257-29b2-46ff-97b4-8299e8a00379</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#logout-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='logout-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>72cafd42-293e-447b-83a1-1df13caf8aee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>logout.php</value>
      <webElementGuid>34ae1e8d-a7a0-4167-9e89-47d85cadaa71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>py-2 px-4-5 mb-3</value>
      <webElementGuid>77173a82-4292-43e4-aeaf-c54b6e5a63c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>logout-button</value>
      <webElementGuid>7b4cac69-18d1-4f02-994d-e61e2d62dfcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;logout-button&quot;)</value>
      <webElementGuid>a25e6160-8279-4a0a-994f-e66fd779b876</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='logout-button']</value>
      <webElementGuid>cced85bd-cb95-4275-bf28-0bd571ed9406</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manajer'])[1]/following::a[2]</value>
      <webElementGuid>20eee863-6d89-47cd-bb77-07407e5b21de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar Karyawan'])[2]/preceding::a[1]</value>
      <webElementGuid>ed025062-d45d-4a6e-8126-b257f349f2d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/preceding::a[2]</value>
      <webElementGuid>448fba7f-52df-47e8-9fec-41bf9c8892a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'logout.php')]</value>
      <webElementGuid>4bf9a834-2086-42f3-945e-1fd1a537b947</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//aside/div/a</value>
      <webElementGuid>221f39ab-8e9a-45a0-9033-f6a783c95ad8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'logout.php' and @id = 'logout-button']</value>
      <webElementGuid>ea6ea28d-a634-454f-9a22-947e7874f1de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
